[pytest]
filterwarnings =
    ignore::DeprecationWarning:fastapi.*:
    ignore::DeprecationWarning:starlette.*:
    ignore::DeprecationWarning:jose.*:
    ignore::PendingDeprecationWarning:starlette.*:
